name: Build Cordova Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Install Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

- name: Initialize Cordova project
  if: steps.check_cordova.outputs.is_cordova_project != 'true'
  run: |
    cordova create cctv-you com.example.cctvyou "CCTV YOU"
    echo "Created new Cordova project"

- name: Add Android platform
  run: |
    cd cctv-you
    cordova platform add android@12.0.0

- name: Build APK
  run: |
    cd cctv-you
    cordova build android --verbose

- name: Upload APK
  uses: actions/upload-artifact@v4
  with:
    name: android-apk
    path: |
      cctv-you/platforms/android/app/build/outputs/apk/debug/*.apk
      cctv-you/platforms/android/app/build/outputs/apk/release/*.apk

