name: Build Cordova Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'  # Using Java 11 instead of 17 for better compatibility
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Install Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Cordova
      run: |
        npm install -g cordova@11.0.0
        cordova --version

    - name: Create Cordova project
      run: |
        cordova create cctv-app com.example.cctvyou "CCTV YOU"
        
    - name: Setup Android SDK tools
      run: |
        mkdir -p $ANDROID_SDK_ROOT
        cd $ANDROID_SDK_ROOT
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/ 2>/dev/null || true
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Add Android platform
      run: |
        cd cctv-app
        cordova platform add android@12.0.0

    - name: Build APK
      run: |
        cd cctv-app
        cordova build android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: |
          cctv-app/platforms/android/app/build/outputs/apk/debug/*.apk
